resources:
  - name: incoming_webhook_rb
    type: IncomingWebhook
    configuration:
      webhookName: incoming_hook_rb
 
pipelines:
  - name: incoming_webhook_demo
    steps:
      - name: start_by_hook
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook_rb
        execution:
          onExecute:
            - echo "job triggered by resource-> $step_triggered_by_resource_name"
            - echo "$res_  - name: incoming_hook_rb_payload" | jq '.' > payload.json
            - echo "$(read_json payload.json my.nested.object)"
