template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: GitRepo_res
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.myRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.myRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

  - name: incoming_webhook_RB_signed_res
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook_RB_signed

pipelines:
  - name: incoming_webhook_RBS_pipe
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook_RB_signed_res
          integrations:
           - name: global_arti

        execution:
            onExecute:
              - echo "$res_incoming_webhook_RB_signed_res_payload" | jq '.' > payload.json
              - rb_name=$(read_json payload.json 'data.release_bundle_name')
              - echo $rb_name
              - rb_ver=$(read_json payload.json 'data.release_bundle_version')
              - echo $rb_ver
              - downloadfile="release-bundles/${rb_name}/${rb_ver}"
              - echo $downloadfile
              - artiserver=$(read_json payload.json 'jpd_origin')  
              - echo $artiserver
              - rest_get="${artiserver}/distribution/api/v1/release_bundle/${rb_name}/${rb_ver}"
              - echo $rest_get
              - rest_auth="${int_global_arti_user}:${int_global_arti_apikey}"
              - echo $rest_auth
              - curl -u $rest_auth "$rest_get"
              - curl -u $rest_auth "$rest_get" | jq '.' > bundle.json
              - cp bundle.json 
              - npm run app.js

              
             
