resources:
  - name: incoming_webhook_rb_res
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook_RB_signed
 
pipelines:
  - name: incoming_webhook_demo
    steps:
      - name: start_by_hook
        type: bash
        configuration:
          inputResources:
            - name: incoming_webhook_rb_res
        execution:
          onExecute:
            - echo "$res_incoming_webhook_demo_payload" | jq '.' > payload.json
            - read_json payload.json "Hello"
