
resources:
  - name: incoming_webhook_rb_res
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook_RB_signed
 
pipelines:
  - name: incoming_webhook_RBS
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: from_artifactory
          integrations:
            - name: myArtifactory
        execution:
            onExecute:
              - echo "$res_from_artifactory_payload" | jq '.' > payload.json
              - rb_name=$(read_json payload.json 'data.release_bundle_name')
              - rb_ver=$(read_json payload.json 'data.release_bundle_version')
              - rb_prop ="${rb_name}/${rb_ver}"
              - echo $rb_prop
