
resources:
  - name: incoming_webhook_RB_signed_res
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook_RB_signed
 
pipelines:
  - name: incoming_webhook_RBS_pipe
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook_RB_signed_res
          integrations:
           - name: global_arti

        execution:
            onExecute:
              - echo "$res_incoming_webhook_RB_signed_res_payload" | jq '.' > payload.json
              - rb_name=$(read_json payload.json 'data.release_bundle_name')
              - echo $rb_name
              - rb_ver=$(read_json payload.json 'data.release_bundle_version')
              - echo $rb_ver
              - downloadfile="release-bundles/${rb_name}/${rb_ver}"
              - echo $downloadfile
              
